export const SAVE_HOTEL_QUERY = 'SAVE_HOTEL_QUERY'
export const INIT_HOTEL_QUERY = 'INIT_HOTEL_QUERY'
export const SAVE_ROOMTYPE_DETAIL = 'SAVE_ROOMTYPE_DETAIL'
export const INIT_ROOMTYPE_DETAIL = 'INIT_ROOMTYPE_DETAIL'
export const SAVE_HOTEL_LIST = 'SAVE_HOTEL_LIST'
export const INIT_HOTEL_LIST = 'INIT_HOTEL_LIST'
export const CLEAR_HOTEL_LIST = 'CLEAR_HOTEL_LIST'
export const GET_OPTIONAL_CITY = 'GET_OPTIONAL_CITY'

